theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
q = ":q"
Q = ":q!"
W = ":wq"
